# site settings
title: Parth Patil
subtitle: homepage
email: parthvin@gmail.com
description: I'm not a great programmer,<br/>I'm a just a programmer with great habits.
url: https://parthvpatil.github.io
baseurl: ''
author:

# street_address:
city: Lafayette
state: IN,
zip_code: 47904
country: USA
phone: +1 765-767-0983

# Google analytics
analytics_id: 'UA-140472706-1'
new_analytics_id: 'G-T2B563BH28'
formspree_api: xeojjedp

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/parth.patil.77
github_url: https://github.com/parth1811
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/parthvpatil18/
linkedin_url: https://www.linkedin.com/in/parth-patil-256291117/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

pulgins:
  'jekyll-watch'
